# Generated by Django 4.2.11 on 2024-10-22 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.asset
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_workspace_and_workspacebase'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.CreateModel(
            name='WorkspaceMemberInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255)),
                ('message', models.TextField(null=True)),
                ('responded_at', models.DateTimeField(null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(20, 'Owner'), (15, 'Admin'), (10, 'Member'), (5, 'Guest')], default=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_member_invite', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Member Invite',
                'verbose_name_plural': 'Workspace Member Invites',
                'db_table': 'workspace_member_invites',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('attributes', models.JSONField(default=dict)),
                ('asset', models.FileField(max_length=800, upload_to=plane.db.models.asset.get_upload_path)),
                ('entity_type', models.CharField(blank=True, choices=[('ISSUE_ATTACHMENT', 'Issue Attachment'), ('ISSUE_DESCRIPTION', 'Issue Description'), ('COMMENT_DESCRIPTION', 'Comment Description'), ('PAGE_DESCRIPTION', 'Page Description'), ('USER_COVER', 'User Cover'), ('USER_AVATAR', 'User Avatar'), ('WORKSPACE_LOGO', 'Workspace Logo'), ('PROJECT_COVER', 'Project Cover'), ('DRAFT_ISSUE_ATTACHMENT', 'Draft Issue Attachment'), ('DRAFT_ISSUE_DESCRIPTION', 'Draft Issue Description')], max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.FloatField(default=0)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('storage_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Asset',
                'verbose_name_plural': 'File Assets',
                'db_table': 'file_assets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatar', to='db.fileasset'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cover_image', to='db.fileasset'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_logo', to='db.fileasset'),
        ),
        migrations.AddConstraint(
            model_name='workspacememberinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email', 'workspace'), name='workspace_member_invite_unique_email_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacememberinvite',
            unique_together={('email', 'workspace', 'deleted_at')},
        ),
    ]
