# Generated by Django 4.2.11 on 2024-11-26 07:15

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.asset
import plane.db.models.exporter
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_module_modulemember_moduleissue_module_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='asset',
            field=models.FileField(max_length=800, storage='uploads/', upload_to=plane.db.models.asset.get_upload_path),
        ),
        migrations.CreateModel(
            name='ExporterHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exporter Name')),
                ('type', models.CharField(choices=[('issue_exports', 'Issue Exports'), ('issue_worklogs', 'Issue Worklogs')], default='issue_exports', max_length=50)),
                ('project', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(default=uuid.uuid4), blank=True, null=True, size=None)),
                ('provider', models.CharField(choices=[('json', 'json'), ('csv', 'csv'), ('xlsx', 'xlsx')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('key', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=800, null=True)),
                ('token', models.CharField(default=plane.db.models.exporter.generate_token, max_length=255, unique=True)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_exporters', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_exporters', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Exporter',
                'verbose_name_plural': 'Exporters',
                'db_table': 'exporters',
                'ordering': ('-created_at',),
            },
        ),
    ]
